apiVersion: v1
kind: Service
metadata:
  name: taskify-redis
  namespace: taskify
spec:
  selector:
    app: taskify-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
