apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskify-web
  namespace: taskify
  labels:
    app: taskify-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: taskify-web
  template:
    metadata:
      labels:
        app: taskify-web
    spec:
      containers:
        - name: taskify-web
          image: jandir/taskify-web:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: taskify-web-nginx-config
