apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskify-api
  namespace: taskify
  labels:
    app: taskify-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: taskify-api
  template:
    metadata:
      labels:
        app: taskify-api
    spec:
      containers:
        - name: taskify-api
          image: jandir/taskify-api:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: taskify-api-configmap
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskify-api-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: rsa-keys
              mountPath: /app/private.pem
              subPath: private.pem
              readOnly: true
            - name: rsa-keys
              mountPath: /app/public.pem
              subPath: public.pem
              readOnly: true
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: rsa-keys
          secret:
            secretName: taskify-api-secret
            items:
              - key: private.pem
                path: private.pem
              - key: public.pem
                path: public.pem
        - name: uploads
          emptyDir: {}
