apiVersion: v1
kind: Service
metadata:
  name: taskify-jaeger
  namespace: taskify
spec:
  selector:
    app: taskify-jaeger
  ports:
    - name: ui
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
  type: ClusterIP
